name: SmallRye Prepare Release

on:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: git author
        run: |
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"

      - uses: radcortez/project-metadata-action@main
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - name: Prepare Gradle
        run: |
          echo "version=${{steps.metadata.outputs.current-version}}" > tools/gradle-plugin/gradle.properties
          git add tools/gradle-plugin/gradle.properties
          git commit -m "Update Gradle plugin version"
          git push

  prepare-release:
    needs: [prepare-gradle]
    name: Prepare Release
    if: ${{ github.event.pull_request.merged == true}}
    uses: smallrye/.github/.github/workflows/prepare-release.yml@main
    secrets: inherit
